name: Production Build & Deploy

on:
  push:
    branches:
      - main # Trigger on every push to main branch

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production

  submit_android:
    type: submit
    params:
      platform: android
      profile: production
      build_id: ${{ needs.build_android.outputs.build_id }}
    needs:
      - build_android
